meta_product_name: "Game-Aware"
meta_title: "Game-Aware - Is this game safe?"
meta_description: "Game-Aware is the quickest and more reliable way to determine if a game is suited for your children."
meta_image: "cover.png" # should exist in `app/assets/images/`
